In [3]:
import numpy as np
import pandas as pd
import keras
import tensorflow as tf

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

import keras.models as km
from keras.models import Sequential
from keras import activations, initializers, regularizers, constraints
from keras.layers import Dense, Activation

In [4]:
df = pd.read_csv("diabetes.csv")

In [5]:
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [6]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [7]:
df.tail()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [8]:
df.shape

(768, 9)

In [9]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [11]:
df.duplicated().sum()

np.int64(0)

In [16]:
df["Outcome"].unique()

array([1, 0])

In [17]:
X = df.drop("Outcome",axis = 1)
y = df["Outcome"]

In [18]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [20]:
X_train.shape

(614, 8)

In [21]:
sc = StandardScaler()

In [22]:
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [24]:
model = Sequential()

In [25]:
model.add(Dense(
    units=16,
    activation="relu",
    input_dim=8
))

In [26]:
model.add(Dense(
    units = 8,
    activation = "relu"
))

In [27]:
model.add(Dense(
    units = 4,
    activation = "relu"
))

In [30]:
model.add(Dense(
    units=1,
    activation="sigmoid"
))

In [31]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_1 (Dense)                      │ (None, 16)                  │             144 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 8)                   │             136 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ (None, 4)                   │              36 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_4 (Dense)                      │ (None, 1)                   │               5 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 321 (1.25 KB)

 Trainable params: 321 (1.25 KB)

 Non-trainable params: 0 (0.00 B)

In [32]:
model.compile(
    optimizer = "adam",
    loss = "binary_crossentropy",
    metrics = ["accuracy"]
)

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [33]:
history = model.fit(X_train, y_train, epochs = 100, batch_size = 32, validation_split = 0.2)

Epoch 1/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - accuracy: 0.6640 - loss: 0.6589 - val_accuracy: 0.6098 - val_loss: 0.6918
Epoch 2/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6640 - loss: 0.6371 - val_accuracy: 0.6098 - val_loss: 0.6695
Epoch 3/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6640 - loss: 0.6177 - val_accuracy: 0.6098 - val_loss: 0.6511
Epoch 4/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6640 - loss: 0.6000 - val_accuracy: 0.6098 - val_loss: 0.6325
Epoch 5/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6640 - loss: 0.5831 - val_accuracy: 0.6098 - val_loss: 0.6172
Epoch 6/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6640 - loss: 0.5681 - val_accuracy: 0.6098 - val_loss: 0.6030
Epoch 7/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6640 - loss: 0.5553 - val_accuracy: 0.6098 - val_loss: 0.5897
Epoch 8/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6640 - loss: 0.5426 - val_accuracy: 0.6098 - val_loss: 0.5805
Epoch 9/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6640 - loss: 0.5318 - val_accuracy: 0.6098 - val_loss: 0.5684
Epoch 10/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6660 - loss: 0.5214 - val_accuracy: 0.6667 - val_loss: 0.5590
Epoch 11/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7006 - loss: 0.5122 - val_accuracy: 0.6829 - val_loss: 0.5499
Epoch 12/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7189 - loss: 0.5052 - val_accuracy: 0.6829 - val_loss: 0.5422
Epoch 13/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7149 - loss: 0.4987 - val_accuracy: 0.6748 - val_loss: 0.5384
Epoch 14/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7251 - loss: 0.4934 - val_accuracy: 0.6911 - val_loss: 0.5331
Epoch 15/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7312 - loss: 0.4886 - val_accuracy: 0.7073 - val_loss: 0.5299
Epoch 16/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7352 - loss: 0.4841 - val_accuracy: 0.7073 - val_loss: 0.5281
Epoch 17/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7434 - loss: 0.4808 - val_accuracy: 0.7154 - val_loss: 0.5266
Epoch 18/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7597 - loss: 0.4779 - val_accuracy: 0.7317 - val_loss: 0.5239
Epoch 19/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7658 - loss: 0.4745 - val_accuracy: 0.7317 - val_loss: 0.5217
Epoch 20/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7637 - loss: 0.4707 - val_accuracy: 0.7317 - val_loss: 0.5216
Epoch 21/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7699 - loss: 0.4675 - val_accuracy: 0.7317 - val_loss: 0.5182
Epoch 22/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7780 - loss: 0.4647 - val_accuracy: 0.7317 - val_loss: 0.5162
Epoch 23/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7862 - loss: 0.4616 - val_accuracy: 0.7398 - val_loss: 0.5156
Epoch 24/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7882 - loss: 0.4594 - val_accuracy: 0.7398 - val_loss: 0.5156
Epoch 25/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7882 - loss: 0.4568 - val_accuracy: 0.7480 - val_loss: 0.5135
Epoch 26/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7984 - loss: 0.4556 - val_accuracy: 0.7398 - val_loss: 0.5134
Epoch 27/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8004 - loss: 0.4535 - val_accuracy: 0.7480 - val_loss: 0.5122
Epoch 28/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8024 - loss: 0.4512 - val_accuracy: 0.7561 - val_loss: 0.5113
Epoch 29/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8045 - loss: 0.4502 - val_accuracy: 0.7642 - val_loss: 0.5093
Epoch 30/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8045 - loss: 0.4475 - val_accuracy: 0.7561 - val_loss: 0.5100
Epoch 31/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8024 - loss: 0.4464 - val_accuracy: 0.7642 - val_loss: 0.5071
Epoch 32/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8024 - loss: 0.4439 - val_accuracy: 0.7642 - val_loss: 0.5111
Epoch 33/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8065 - loss: 0.4427 - val_accuracy: 0.7642 - val_loss: 0.5085
Epoch 34/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8086 - loss: 0.4412 - val_accuracy: 0.7642 - val_loss: 0.5088
Epoch 35/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8106 - loss: 0.4388 - val_accuracy: 0.7642 - val_loss: 0.5104
Epoch 36/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8147 - loss: 0.4377 - val_accuracy: 0.7561 - val_loss: 0.5079
Epoch 37/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8167 - loss: 0.4363 - val_accuracy: 0.7724 - val_loss: 0.5086
Epoch 38/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8106 - loss: 0.4339 - val_accuracy: 0.7724 - val_loss: 0.5101
Epoch 39/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8228 - loss: 0.4318 - val_accuracy: 0.7642 - val_loss: 0.5074
Epoch 40/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8208 - loss: 0.4307 - val_accuracy: 0.7561 - val_loss: 0.5070
Epoch 41/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8187 - loss: 0.4297 - val_accuracy: 0.7805 - val_loss: 0.5070
Epoch 42/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8208 - loss: 0.4274 - val_accuracy: 0.7724 - val_loss: 0.5090
Epoch 43/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8147 - loss: 0.4260 - val_accuracy: 0.7724 - val_loss: 0.5078
Epoch 44/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8269 - loss: 0.4246 - val_accuracy: 0.7561 - val_loss: 0.5047
Epoch 45/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8269 - loss: 0.4225 - val_accuracy: 0.7642 - val_loss: 0.5110
Epoch 46/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8167 - loss: 0.4222 - val_accuracy: 0.7561 - val_loss: 0.5103
Epoch 47/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8310 - loss: 0.4200 - val_accuracy: 0.7480 - val_loss: 0.5041
Epoch 48/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8350 - loss: 0.4192 - val_accuracy: 0.7480 - val_loss: 0.5054
Epoch 49/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8248 - loss: 0.4193 - val_accuracy: 0.7805 - val_loss: 0.5120
Epoch 50/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8350 - loss: 0.4169 - val_accuracy: 0.7398 - val_loss: 0.5011
Epoch 51/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8269 - loss: 0.4153 - val_accuracy: 0.7561 - val_loss: 0.5065
Epoch 52/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8350 - loss: 0.4138 - val_accuracy: 0.7642 - val_loss: 0.5070
Epoch 53/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8350 - loss: 0.4120 - val_accuracy: 0.7480 - val_loss: 0.5044
Epoch 54/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8391 - loss: 0.4110 - val_accuracy: 0.7561 - val_loss: 0.5048
Epoch 55/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8330 - loss: 0.4092 - val_accuracy: 0.7561 - val_loss: 0.5023
Epoch 56/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8350 - loss: 0.4080 - val_accuracy: 0.7561 - val_loss: 0.5035
Epoch 57/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8432 - loss: 0.4085 - val_accuracy: 0.7480 - val_loss: 0.5056
Epoch 58/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8452 - loss: 0.4059 - val_accuracy: 0.7561 - val_loss: 0.5042
Epoch 59/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8452 - loss: 0.4055 - val_accuracy: 0.7642 - val_loss: 0.5046
Epoch 60/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8411 - loss: 0.4041 - val_accuracy: 0.7561 - val_loss: 0.5058
Epoch 61/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8452 - loss: 0.4024 - val_accuracy: 0.7561 - val_loss: 0.5069
Epoch 62/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8493 - loss: 0.4012 - val_accuracy: 0.7561 - val_loss: 0.5049
Epoch 63/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8513 - loss: 0.4004 - val_accuracy: 0.7561 - val_loss: 0.5069
Epoch 64/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8452 - loss: 0.3996 - val_accuracy: 0.7642 - val_loss: 0.5057
Epoch 65/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8493 - loss: 0.3985 - val_accuracy: 0.7398 - val_loss: 0.5057
Epoch 66/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8513 - loss: 0.3967 - val_accuracy: 0.7561 - val_loss: 0.5072
Epoch 67/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8513 - loss: 0.3965 - val_accuracy: 0.7561 - val_loss: 0.5081
Epoch 68/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8554 - loss: 0.3951 - val_accuracy: 0.7561 - val_loss: 0.5075
Epoch 69/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8473 - loss: 0.3941 - val_accuracy: 0.7398 - val_loss: 0.5022
Epoch 70/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8493 - loss: 0.3935 - val_accuracy: 0.7480 - val_loss: 0.5068
Epoch 71/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8534 - loss: 0.3927 - val_accuracy: 0.7724 - val_loss: 0.5119
Epoch 72/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8534 - loss: 0.3918 - val_accuracy: 0.7480 - val_loss: 0.5090
Epoch 73/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8534 - loss: 0.3901 - val_accuracy: 0.7642 - val_loss: 0.5147
Epoch 74/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8554 - loss: 0.3885 - val_accuracy: 0.7724 - val_loss: 0.5154
Epoch 75/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8554 - loss: 0.3884 - val_accuracy: 0.7561 - val_loss: 0.5120
Epoch 76/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8534 - loss: 0.3876 - val_accuracy: 0.7561 - val_loss: 0.5148
Epoch 77/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8574 - loss: 0.3859 - val_accuracy: 0.7561 - val_loss: 0.5113
Epoch 78/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8615 - loss: 0.3848 - val_accuracy: 0.7642 - val_loss: 0.5152
Epoch 79/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8595 - loss: 0.3852 - val_accuracy: 0.7561 - val_loss: 0.5150
Epoch 80/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8574 - loss: 0.3839 - val_accuracy: 0.7561 - val_loss: 0.5172
Epoch 81/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8595 - loss: 0.3830 - val_accuracy: 0.7480 - val_loss: 0.5191
Epoch 82/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8574 - loss: 0.3819 - val_accuracy: 0.7561 - val_loss: 0.5185
Epoch 83/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8595 - loss: 0.3810 - val_accuracy: 0.7561 - val_loss: 0.5215
Epoch 84/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8534 - loss: 0.3808 - val_accuracy: 0.7561 - val_loss: 0.5218
Epoch 85/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8513 - loss: 0.3795 - val_accuracy: 0.7642 - val_loss: 0.5239
Epoch 86/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8595 - loss: 0.3790 - val_accuracy: 0.7642 - val_loss: 0.5249
Epoch 87/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8595 - loss: 0.3794 - val_accuracy: 0.7561 - val_loss: 0.5175
Epoch 88/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8574 - loss: 0.3767 - val_accuracy: 0.7561 - val_loss: 0.5297
Epoch 89/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8615 - loss: 0.3750 - val_accuracy: 0.7561 - val_loss: 0.5198
Epoch 90/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8615 - loss: 0.3746 - val_accuracy: 0.7480 - val_loss: 0.5215
Epoch 91/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8615 - loss: 0.3747 - val_accuracy: 0.7561 - val_loss: 0.5229
Epoch 92/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8635 - loss: 0.3742 - val_accuracy: 0.7561 - val_loss: 0.5196
Epoch 93/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8595 - loss: 0.3721 - val_accuracy: 0.7561 - val_loss: 0.5242
Epoch 94/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8635 - loss: 0.3709 - val_accuracy: 0.7561 - val_loss: 0.5215
Epoch 95/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8656 - loss: 0.3701 - val_accuracy: 0.7561 - val_loss: 0.5203
Epoch 96/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8635 - loss: 0.3703 - val_accuracy: 0.7561 - val_loss: 0.5290
Epoch 97/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8615 - loss: 0.3684 - val_accuracy: 0.7561 - val_loss: 0.5239
Epoch 98/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8615 - loss: 0.3685 - val_accuracy: 0.7642 - val_loss: 0.5360
Epoch 99/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8697 - loss: 0.3666 - val_accuracy: 0.7561 - val_loss: 0.5247
Epoch 100/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8656 - loss: 0.3671 - val_accuracy: 0.7561 - val_loss: 0.5269

In [34]:
y_pred = model.predict(X_test)

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step

In [35]:
y_pred = (y_pred > 0.5)

In [40]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [39]:
accuracy = accuracy_score(y_test, y_pred)
cm = confusion_matrix(y_test, y_pred)
print(accuracy)
print(cm)

0.7207792207792207
[[78 21]
 [22 33]]

In [41]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.78      0.79      0.78        99
           1       0.61      0.60      0.61        55

    accuracy                           0.72       154
   macro avg       0.70      0.69      0.69       154
weighted avg       0.72      0.72      0.72       154

In [44]:
model.save("diabetes_ann_model.keras")

In [45]:
import pickle
pickle.dump(sc,open("scaler.pkl", "wb"))